stages:
  - build
  - deploy

build-job:
  stage: build
  image: amazon/aws-cli
  before_script:
    - echo "Test"
    - aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
    - aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
    - aws configure set region $AWS_REGION
    - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin 381491971380.dkr.ecr.us-east-1.amazonaws.com
  script:
    - docker build -t csci5409-ta .
    - docker tag csci5409-ta:latest 381491971380.dkr.ecr.us-east-1.amazonaws.com/csci5409-ta:latest

deploy-job:
  stage: deploy
  image: docker:stable
  script: docker push 381491971380.dkr.ecr.us-east-1.amazonaws.com/csci5409-ta:latest
  only:
    - main